name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.Vercel_Token }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.Vercel_Token }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.Vercel_Token }}

      - name: Deploy to Vercel (extra paso con nombre personalizado)
        env:
          VERCEL_TOKEN: ${{ secrets.Vercel_Token }}
        run: |
          vercel pull --yes --environment=production --token=$Vercel_Token
          vercel --prod --yes --token=$Vercel_Token --name=hola-mundo-en-html


  
